# Singleton service factory configuration/IoC injection
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: oracle.jdbc.pool.OracleDataSource
      jdbcUrl: jdbc:oracle:thin:@oracle:1521:XE
      username: SYSTEM
      password: oracle
      maximumPoolSize: 2
      useServerPrepStmts: true
      cachePrepStmts: true
      cacheCallableStmts: true
      prepStmtCacheSize: 10
      prepStmtCacheSqlLimit: 2048
      connectionTimeout: 2000
- com.networknt.eventuate.jdbc.EventuateSchema:
  - com.networknt.eventuate.jdbc.EventuateSchema
- com.networknt.tram.cdc.polling.connector.MessagePollingDataProvider:
  - com.networknt.tram.cdc.polling.connector.MessagePollingDataProvider
- com.networknt.eventuate.server.common.PublishingStrategy:
  - com.networknt.tram.cdc.mysql.connector.MessageWithDestinationPublishingStrategy
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.networknt.tram.cdc.server.CdcServer
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.tram.cdc.server.CdcServerStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.tram.cdc.server.CdcServerShutdownHookProvider
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
