# Singleton service factory configuration/IoC injection
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: jdbc:mysql://mysql:3306/eventuate?useSSL=false
      username: mysqluser
      password: mysqlpw
      maximumPoolSize: 4
      useServerPrepStmts: true
      cachePrepStmts: true
      cacheCallableStmts: true
      prepStmtCacheSize: 4096
      prepStmtCacheSqlLimit: 2048
- com.networknt.eventuate.jdbc.EventuateSchema: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::eventuateSchema
- com.networknt.eventuate.cdc.mysql.binlog.SourceTableNameSupplier: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::sourceTableNameSupplier
- com.networknt.eventuate.jdbc.EventuateJdbcAccess:
  - com.networknt.eventuate.server.jdbckafkastore.EventuateLocalJdbcAccess
- com.networknt.eventuate.cdc.mysql.binlog.IWriteRowsEventDataParser: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::eventDataParser
- com.networknt.eventuate.cdc.mysql.binlog.MySqlBinaryLogClient: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::mySqlBinaryLogClient
- com.networknt.eventuate.kafka.producer.EventuateKafkaProducer: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::eventuateKafkaProducer
- com.networknt.eventuate.cdc.mysql.binlog.DatabaseBinlogOffsetKafkaStore: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::binlogOffsetKafkaStore
- com.networknt.eventuate.cdc.mysql.binlog.DebeziumBinlogOffsetKafkaStore: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::debeziumBinlogOffsetKafkaStore
- com.networknt.eventuate.server.common.PublishingStrategy:
  - com.networknt.tram.cdc.mysql.connector.MessageWithDestinationPublishingStrategy
- com.networknt.eventuate.server.common.CdcProcessor: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::mySQLCdcProcessor
- com.networknt.eventuate.server.common.CdcKafkaPublisher: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::mySQLCdcKafkaPublisher
- org.apache.curator.framework.CuratorFramework: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::curatorFramework
- com.networknt.eventuate.server.common.EventTableChangesToAggregateTopicTranslator: com.networknt.tram.cdc.server.MySqlTramCdcServiceInitializer::mySqlEventTableChangesToAggregateTopicTranslator
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.networknt.tram.cdc.server.CdcServer
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - com.networknt.tram.cdc.server.CdcServerStartupHookProvider
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.tram.cdc.server.CdcServerShutdownHookProvider
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
