tokenization:
  jdbcUrl: jdbc:mysql://198.55.49.187:3306/tokenization?useSSL=false
  username: mysqluser
  password: mysqlpw
  parameters:
    maximumPoolSize: 2
    useServerPrepStmts: true
    cachePrepStmts: true
    cacheCallableStmts: true
    prepStmtCacheSize: 40
    prepStmtCacheSqlLimit: 20
vault000:
  jdbcUrl: jdbc:mysql://198.55.49.187:3306/vault000?useSSL=false
  username: mysqluser
  password: mysqlpw
  parameters:
    maximumPoolSize: 2
    useServerPrepStmts: true
    cachePrepStmts: true
    cacheCallableStmts: true
    prepStmtCacheSize: 40
    prepStmtCacheSqlLimit: 20
